//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Wedding
	/// Data Source    : localhost
	/// Server Version : 5.7.9-log
	/// </summary>
	public partial class WeddingDB : LinqToDB.Data.DataConnection
	{
		public ITable<group>                                         groups                                        { get { return this.GetTable<group>(); } }
		public ITable<host_summary>                                  host_summary                                  { get { return this.GetTable<host_summary>(); } }
		public ITable<host_summary_by_file_io>                       host_summary_by_file_io                       { get { return this.GetTable<host_summary_by_file_io>(); } }
		public ITable<host_summary_by_file_io_type>                  host_summary_by_file_io_type                  { get { return this.GetTable<host_summary_by_file_io_type>(); } }
		public ITable<host_summary_by_stages>                        host_summary_by_stages                        { get { return this.GetTable<host_summary_by_stages>(); } }
		public ITable<host_summary_by_statement_latency>             host_summary_by_statement_latency             { get { return this.GetTable<host_summary_by_statement_latency>(); } }
		public ITable<host_summary_by_statement_type>                host_summary_by_statement_type                { get { return this.GetTable<host_summary_by_statement_type>(); } }
		public ITable<innodb_buffer_stats_by_schema>                 innodb_buffer_stats_by_schema                 { get { return this.GetTable<innodb_buffer_stats_by_schema>(); } }
		public ITable<innodb_buffer_stats_by_table>                  innodb_buffer_stats_by_table                  { get { return this.GetTable<innodb_buffer_stats_by_table>(); } }
		public ITable<innodb_lock_waits>                             innodb_lock_waits                             { get { return this.GetTable<innodb_lock_waits>(); } }
		public ITable<io_by_thread_by_latency>                       io_by_thread_by_latency                       { get { return this.GetTable<io_by_thread_by_latency>(); } }
		public ITable<io_global_by_file_by_bytes>                    io_global_by_file_by_bytes                    { get { return this.GetTable<io_global_by_file_by_bytes>(); } }
		public ITable<io_global_by_file_by_latency>                  io_global_by_file_by_latency                  { get { return this.GetTable<io_global_by_file_by_latency>(); } }
		public ITable<io_global_by_wait_by_bytes>                    io_global_by_wait_by_bytes                    { get { return this.GetTable<io_global_by_wait_by_bytes>(); } }
		public ITable<io_global_by_wait_by_latency>                  io_global_by_wait_by_latency                  { get { return this.GetTable<io_global_by_wait_by_latency>(); } }
		public ITable<latest_file_io>                                latest_file_io                                { get { return this.GetTable<latest_file_io>(); } }
		public ITable<memory_by_host_by_current_bytes>               memory_by_host_by_current_bytes               { get { return this.GetTable<memory_by_host_by_current_bytes>(); } }
		public ITable<memory_by_thread_by_current_bytes>             memory_by_thread_by_current_bytes             { get { return this.GetTable<memory_by_thread_by_current_bytes>(); } }
		public ITable<memory_by_user_by_current_bytes>               memory_by_user_by_current_bytes               { get { return this.GetTable<memory_by_user_by_current_bytes>(); } }
		public ITable<memory_global_by_current_bytes>                memory_global_by_current_bytes                { get { return this.GetTable<memory_global_by_current_bytes>(); } }
		public ITable<memory_global_total>                           memory_global_total                           { get { return this.GetTable<memory_global_total>(); } }
		public ITable<metric>                                        metrics                                       { get { return this.GetTable<metric>(); } }
		public ITable<person>                                        people                                        { get { return this.GetTable<person>(); } }
		public ITable<processlist>                                   processlists                                  { get { return this.GetTable<processlist>(); } }
		public ITable<ps_check_lost_instrumentation>                 ps_check_lost_instrumentation                 { get { return this.GetTable<ps_check_lost_instrumentation>(); } }
		public ITable<rsvp_status>                                   rsvp_status                                   { get { return this.GetTable<rsvp_status>(); } }
		public ITable<schema_auto_increment_columns>                 schema_auto_increment_columns                 { get { return this.GetTable<schema_auto_increment_columns>(); } }
		public ITable<schema_index_statistics>                       schema_index_statistics                       { get { return this.GetTable<schema_index_statistics>(); } }
		public ITable<schema_object_overview>                        schema_object_overview                        { get { return this.GetTable<schema_object_overview>(); } }
		public ITable<schema_redundant_indexes>                      schema_redundant_indexes                      { get { return this.GetTable<schema_redundant_indexes>(); } }
		public ITable<schema_table_lock_waits>                       schema_table_lock_waits                       { get { return this.GetTable<schema_table_lock_waits>(); } }
		public ITable<schema_table_statistics>                       schema_table_statistics                       { get { return this.GetTable<schema_table_statistics>(); } }
		public ITable<schema_table_statistics_with_buffer>           schema_table_statistics_with_buffer           { get { return this.GetTable<schema_table_statistics_with_buffer>(); } }
		public ITable<schema_tables_with_full_table_scans>           schema_tables_with_full_table_scans           { get { return this.GetTable<schema_tables_with_full_table_scans>(); } }
		public ITable<schema_unused_indexes>                         schema_unused_indexes                         { get { return this.GetTable<schema_unused_indexes>(); } }
		public ITable<session>                                       sessions                                      { get { return this.GetTable<session>(); } }
		public ITable<session_ssl_status>                            session_ssl_status                            { get { return this.GetTable<session_ssl_status>(); } }
		public ITable<statement_analysis>                            statement_analysis                            { get { return this.GetTable<statement_analysis>(); } }
		public ITable<statements_with_errors_or_warnings>            statements_with_errors_or_warnings            { get { return this.GetTable<statements_with_errors_or_warnings>(); } }
		public ITable<statements_with_full_table_scans>              statements_with_full_table_scans              { get { return this.GetTable<statements_with_full_table_scans>(); } }
		public ITable<statements_with_runtimes_in_95th_percentile>   statements_with_runtimes_in_95th_percentile   { get { return this.GetTable<statements_with_runtimes_in_95th_percentile>(); } }
		public ITable<statements_with_sorting>                       statements_with_sorting                       { get { return this.GetTable<statements_with_sorting>(); } }
		public ITable<statements_with_temp_tables>                   statements_with_temp_tables                   { get { return this.GetTable<statements_with_temp_tables>(); } }
		public ITable<twilio_messaging>                              twilio_messaging                              { get { return this.GetTable<twilio_messaging>(); } }
		public ITable<user_summary>                                  user_summary                                  { get { return this.GetTable<user_summary>(); } }
		public ITable<user_summary_by_file_io>                       user_summary_by_file_io                       { get { return this.GetTable<user_summary_by_file_io>(); } }
		public ITable<user_summary_by_file_io_type>                  user_summary_by_file_io_type                  { get { return this.GetTable<user_summary_by_file_io_type>(); } }
		public ITable<user_summary_by_stages>                        user_summary_by_stages                        { get { return this.GetTable<user_summary_by_stages>(); } }
		public ITable<user_summary_by_statement_latency>             user_summary_by_statement_latency             { get { return this.GetTable<user_summary_by_statement_latency>(); } }
		public ITable<user_summary_by_statement_type>                user_summary_by_statement_type                { get { return this.GetTable<user_summary_by_statement_type>(); } }
		public ITable<version>                                       versions                                      { get { return this.GetTable<version>(); } }
		public ITable<wait_classes_global_by_avg_latency>            wait_classes_global_by_avg_latency            { get { return this.GetTable<wait_classes_global_by_avg_latency>(); } }
		public ITable<wait_classes_global_by_latency>                wait_classes_global_by_latency                { get { return this.GetTable<wait_classes_global_by_latency>(); } }
		public ITable<waits_by_host_by_latency>                      waits_by_host_by_latency                      { get { return this.GetTable<waits_by_host_by_latency>(); } }
		public ITable<waits_by_user_by_latency>                      waits_by_user_by_latency                      { get { return this.GetTable<waits_by_user_by_latency>(); } }
		public ITable<waits_global_by_latency>                       waits_global_by_latency                       { get { return this.GetTable<waits_global_by_latency>(); } }
		public ITable<x_host_summary>                                x_host_summary                                { get { return this.GetTable<x_host_summary>(); } }
		public ITable<x_host_summary_by_file_io>                     x_host_summary_by_file_io                     { get { return this.GetTable<x_host_summary_by_file_io>(); } }
		public ITable<x_host_summary_by_file_io_type>                x_host_summary_by_file_io_type                { get { return this.GetTable<x_host_summary_by_file_io_type>(); } }
		public ITable<x_host_summary_by_stages>                      x_host_summary_by_stages                      { get { return this.GetTable<x_host_summary_by_stages>(); } }
		public ITable<x_host_summary_by_statement_latency>           x_host_summary_by_statement_latency           { get { return this.GetTable<x_host_summary_by_statement_latency>(); } }
		public ITable<x_host_summary_by_statement_type>              x_host_summary_by_statement_type              { get { return this.GetTable<x_host_summary_by_statement_type>(); } }
		public ITable<x_innodb_buffer_stats_by_schema>               x_innodb_buffer_stats_by_schema               { get { return this.GetTable<x_innodb_buffer_stats_by_schema>(); } }
		public ITable<x_innodb_buffer_stats_by_table>                x_innodb_buffer_stats_by_table                { get { return this.GetTable<x_innodb_buffer_stats_by_table>(); } }
		public ITable<x_innodb_lock_waits>                           x_innodb_lock_waits                           { get { return this.GetTable<x_innodb_lock_waits>(); } }
		public ITable<x_io_by_thread_by_latency>                     x_io_by_thread_by_latency                     { get { return this.GetTable<x_io_by_thread_by_latency>(); } }
		public ITable<x_io_global_by_file_by_bytes>                  x_io_global_by_file_by_bytes                  { get { return this.GetTable<x_io_global_by_file_by_bytes>(); } }
		public ITable<x_io_global_by_file_by_latency>                x_io_global_by_file_by_latency                { get { return this.GetTable<x_io_global_by_file_by_latency>(); } }
		public ITable<x_io_global_by_wait_by_bytes>                  x_io_global_by_wait_by_bytes                  { get { return this.GetTable<x_io_global_by_wait_by_bytes>(); } }
		public ITable<x_io_global_by_wait_by_latency>                x_io_global_by_wait_by_latency                { get { return this.GetTable<x_io_global_by_wait_by_latency>(); } }
		public ITable<x_latest_file_io>                              x_latest_file_io                              { get { return this.GetTable<x_latest_file_io>(); } }
		public ITable<x_memory_by_host_by_current_bytes>             x_memory_by_host_by_current_bytes             { get { return this.GetTable<x_memory_by_host_by_current_bytes>(); } }
		public ITable<x_memory_by_thread_by_current_bytes>           x_memory_by_thread_by_current_bytes           { get { return this.GetTable<x_memory_by_thread_by_current_bytes>(); } }
		public ITable<x_memory_by_user_by_current_bytes>             x_memory_by_user_by_current_bytes             { get { return this.GetTable<x_memory_by_user_by_current_bytes>(); } }
		public ITable<x_memory_global_by_current_bytes>              x_memory_global_by_current_bytes              { get { return this.GetTable<x_memory_global_by_current_bytes>(); } }
		public ITable<x_memory_global_total>                         x_memory_global_total                         { get { return this.GetTable<x_memory_global_total>(); } }
		public ITable<x_processlist>                                 x_processlist                                 { get { return this.GetTable<x_processlist>(); } }
		public ITable<x_ps_digest_95th_percentile_by_avg_us>         x_ps_digest_95th_percentile_by_avg_us         { get { return this.GetTable<x_ps_digest_95th_percentile_by_avg_us>(); } }
		public ITable<x_ps_digest_avg_latency_distribution>          x_ps_digest_avg_latency_distribution          { get { return this.GetTable<x_ps_digest_avg_latency_distribution>(); } }
		public ITable<x_ps_schema_table_statistics_io>               x_ps_schema_table_statistics_io               { get { return this.GetTable<x_ps_schema_table_statistics_io>(); } }
		public ITable<x_schema_flattened_keys>                       x_schema_flattened_keys                       { get { return this.GetTable<x_schema_flattened_keys>(); } }
		public ITable<x_schema_index_statistics>                     x_schema_index_statistics                     { get { return this.GetTable<x_schema_index_statistics>(); } }
		public ITable<x_schema_table_lock_waits>                     x_schema_table_lock_waits                     { get { return this.GetTable<x_schema_table_lock_waits>(); } }
		public ITable<x_schema_table_statistics>                     x_schema_table_statistics                     { get { return this.GetTable<x_schema_table_statistics>(); } }
		public ITable<x_schema_table_statistics_with_buffer>         x_schema_table_statistics_with_buffer         { get { return this.GetTable<x_schema_table_statistics_with_buffer>(); } }
		public ITable<x_schema_tables_with_full_table_scans>         x_schema_tables_with_full_table_scans         { get { return this.GetTable<x_schema_tables_with_full_table_scans>(); } }
		public ITable<x_session>                                     x_session                                     { get { return this.GetTable<x_session>(); } }
		public ITable<x_statement_analysis>                          x_statement_analysis                          { get { return this.GetTable<x_statement_analysis>(); } }
		public ITable<x_statements_with_errors_or_warnings>          x_statements_with_errors_or_warnings          { get { return this.GetTable<x_statements_with_errors_or_warnings>(); } }
		public ITable<x_statements_with_full_table_scans>            x_statements_with_full_table_scans            { get { return this.GetTable<x_statements_with_full_table_scans>(); } }
		public ITable<x_statements_with_runtimes_in_95th_percentile> x_statements_with_runtimes_in_95th_percentile { get { return this.GetTable<x_statements_with_runtimes_in_95th_percentile>(); } }
		public ITable<x_statements_with_sorting>                     x_statements_with_sorting                     { get { return this.GetTable<x_statements_with_sorting>(); } }
		public ITable<x_statements_with_temp_tables>                 x_statements_with_temp_tables                 { get { return this.GetTable<x_statements_with_temp_tables>(); } }
		public ITable<x_user_summary>                                x_user_summary                                { get { return this.GetTable<x_user_summary>(); } }
		public ITable<x_user_summary_by_file_io>                     x_user_summary_by_file_io                     { get { return this.GetTable<x_user_summary_by_file_io>(); } }
		public ITable<x_user_summary_by_file_io_type>                x_user_summary_by_file_io_type                { get { return this.GetTable<x_user_summary_by_file_io_type>(); } }
		public ITable<x_user_summary_by_stages>                      x_user_summary_by_stages                      { get { return this.GetTable<x_user_summary_by_stages>(); } }
		public ITable<x_user_summary_by_statement_latency>           x_user_summary_by_statement_latency           { get { return this.GetTable<x_user_summary_by_statement_latency>(); } }
		public ITable<x_user_summary_by_statement_type>              x_user_summary_by_statement_type              { get { return this.GetTable<x_user_summary_by_statement_type>(); } }
		public ITable<x_wait_classes_global_by_avg_latency>          x_wait_classes_global_by_avg_latency          { get { return this.GetTable<x_wait_classes_global_by_avg_latency>(); } }
		public ITable<x_wait_classes_global_by_latency>              x_wait_classes_global_by_latency              { get { return this.GetTable<x_wait_classes_global_by_latency>(); } }
		public ITable<x_waits_by_host_by_latency>                    x_waits_by_host_by_latency                    { get { return this.GetTable<x_waits_by_host_by_latency>(); } }
		public ITable<x_waits_by_user_by_latency>                    x_waits_by_user_by_latency                    { get { return this.GetTable<x_waits_by_user_by_latency>(); } }
		public ITable<x_waits_global_by_latency>                     x_waits_global_by_latency                     { get { return this.GetTable<x_waits_global_by_latency>(); } }

		public WeddingDB()
		{
			InitDataContext();
		}

		public WeddingDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("group")]
	public partial class group
	{
		[PrimaryKey, Identity] public int    id                 { get; set; } // int(11)
		[Column,     Nullable] public int?   rsvp_status        { get; set; } // int(11)
		[Column,     Nullable] public int?   hotel_rooms_needed { get; set; } // int(11)
		[Column,     Nullable] public string name               { get; set; } // varchar(50)
		[Column,     Nullable] public string address            { get; set; } // varchar(255)

		#region Associations

		/// <summary>
		/// fk_group_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="group_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<person> fkids { get; set; }

		#endregion
	}

	// View
	[Table("host_summary")]
	public partial class host_summary
	{
	}

	// View
	[Table("host_summary_by_file_io")]
	public partial class host_summary_by_file_io
	{
	}

	// View
	[Table("host_summary_by_file_io_type")]
	public partial class host_summary_by_file_io_type
	{
	}

	// View
	[Table("host_summary_by_stages")]
	public partial class host_summary_by_stages
	{
	}

	// View
	[Table("host_summary_by_statement_latency")]
	public partial class host_summary_by_statement_latency
	{
	}

	// View
	[Table("host_summary_by_statement_type")]
	public partial class host_summary_by_statement_type
	{
	}

	// View
	[Table("innodb_buffer_stats_by_schema")]
	public partial class innodb_buffer_stats_by_schema
	{
	}

	// View
	[Table("innodb_buffer_stats_by_table")]
	public partial class innodb_buffer_stats_by_table
	{
	}

	// View
	[Table("innodb_lock_waits")]
	public partial class innodb_lock_waits
	{
	}

	// View
	[Table("io_by_thread_by_latency")]
	public partial class io_by_thread_by_latency
	{
	}

	// View
	[Table("io_global_by_file_by_bytes")]
	public partial class io_global_by_file_by_bytes
	{
	}

	// View
	[Table("io_global_by_file_by_latency")]
	public partial class io_global_by_file_by_latency
	{
	}

	// View
	[Table("io_global_by_wait_by_bytes")]
	public partial class io_global_by_wait_by_bytes
	{
	}

	// View
	[Table("io_global_by_wait_by_latency")]
	public partial class io_global_by_wait_by_latency
	{
	}

	// View
	[Table("latest_file_io")]
	public partial class latest_file_io
	{
	}

	// View
	[Table("memory_by_host_by_current_bytes")]
	public partial class memory_by_host_by_current_bytes
	{
	}

	// View
	[Table("memory_by_thread_by_current_bytes")]
	public partial class memory_by_thread_by_current_bytes
	{
	}

	// View
	[Table("memory_by_user_by_current_bytes")]
	public partial class memory_by_user_by_current_bytes
	{
	}

	// View
	[Table("memory_global_by_current_bytes")]
	public partial class memory_global_by_current_bytes
	{
	}

	// View
	[Table("memory_global_total")]
	public partial class memory_global_total
	{
	}

	// View
	[Table("metrics")]
	public partial class metric
	{
	}

	[Table("person")]
	public partial class person
	{
		[PrimaryKey, Identity   ] public int    id                   { get; set; } // int(11)
		[Column,     NotNull    ] public string name                 { get; set; } // varchar(50)
		[Column,        Nullable] public int?   group_id             { get; set; } // int(11)
		[Column,        Nullable] public string instagram            { get; set; } // varchar(50)
		[Column,        Nullable] public string phone_number         { get; set; } // varchar(10)
		[Column,        Nullable] public int?   wedding_rsvp_status  { get; set; } // int(11)
		[Column,        Nullable] public int?   r_dinner_rsvp_status { get; set; } // int(11)
		[Column,        Nullable] public ulong? is_invited_r_dinner  { get; set; } // bit(1)
		[Column,        Nullable] public string email                { get; set; } // varchar(50)

		#region Associations

		/// <summary>
		/// fk_group_id
		/// </summary>
		[Association(ThisKey="group_id", OtherKey="id", CanBeNull=true, KeyName="fk_group_id", BackReferenceName="fkids")]
		public group fkgroupid { get; set; }

		/// <summary>
		/// fk_rsvp_dinner
		/// </summary>
		[Association(ThisKey="wedding_rsvp_status", OtherKey="id", CanBeNull=true, KeyName="fk_rsvp_dinner", BackReferenceName="fkrsvpdinners")]
		public rsvp_status fkrsvpdinner { get; set; }

		/// <summary>
		/// fk_rsvp_wedding
		/// </summary>
		[Association(ThisKey="r_dinner_rsvp_status", OtherKey="id", CanBeNull=true, KeyName="fk_rsvp_wedding", BackReferenceName="fkrsvpweddings")]
		public rsvp_status fkrsvpwedding { get; set; }

		/// <summary>
		/// fk_phone_BackReference
		/// </summary>
		[Association(ThisKey="phone_number", OtherKey="phone_number", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<twilio_messaging> fkphones { get; set; }

		#endregion
	}

	// View
	[Table("processlist")]
	public partial class processlist
	{
	}

	// View
	[Table("ps_check_lost_instrumentation")]
	public partial class ps_check_lost_instrumentation
	{
	}

	[Table("rsvp_status")]
	public partial class rsvp_status
	{
		[PrimaryKey, NotNull    ] public int    id     { get; set; } // int(11)
		[Column,        Nullable] public string status { get; set; } // varchar(50)

		#region Associations

		/// <summary>
		/// fk_rsvp_dinner_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="wedding_rsvp_status", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<person> fkrsvpdinners { get; set; }

		/// <summary>
		/// fk_rsvp_wedding_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="r_dinner_rsvp_status", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<person> fkrsvpweddings { get; set; }

		#endregion
	}

	// View
	[Table("schema_auto_increment_columns")]
	public partial class schema_auto_increment_columns
	{
	}

	// View
	[Table("schema_index_statistics")]
	public partial class schema_index_statistics
	{
	}

	// View
	[Table("schema_object_overview")]
	public partial class schema_object_overview
	{
	}

	// View
	[Table("schema_redundant_indexes")]
	public partial class schema_redundant_indexes
	{
	}

	// View
	[Table("schema_table_lock_waits")]
	public partial class schema_table_lock_waits
	{
	}

	// View
	[Table("schema_table_statistics")]
	public partial class schema_table_statistics
	{
	}

	// View
	[Table("schema_table_statistics_with_buffer")]
	public partial class schema_table_statistics_with_buffer
	{
	}

	// View
	[Table("schema_tables_with_full_table_scans")]
	public partial class schema_tables_with_full_table_scans
	{
	}

	// View
	[Table("schema_unused_indexes")]
	public partial class schema_unused_indexes
	{
	}

	// View
	[Table("session")]
	public partial class session
	{
	}

	// View
	[Table("session_ssl_status")]
	public partial class session_ssl_status
	{
	}

	// View
	[Table("statement_analysis")]
	public partial class statement_analysis
	{
	}

	// View
	[Table("statements_with_errors_or_warnings")]
	public partial class statements_with_errors_or_warnings
	{
	}

	// View
	[Table("statements_with_full_table_scans")]
	public partial class statements_with_full_table_scans
	{
	}

	// View
	[Table("statements_with_runtimes_in_95th_percentile")]
	public partial class statements_with_runtimes_in_95th_percentile
	{
	}

	// View
	[Table("statements_with_sorting")]
	public partial class statements_with_sorting
	{
	}

	// View
	[Table("statements_with_temp_tables")]
	public partial class statements_with_temp_tables
	{
	}

	[Table("twilio_messaging")]
	public partial class twilio_messaging
	{
		[Column, NotNull] public string   phone_number { get; set; } // varchar(10)
		[Column, NotNull] public DateTime date         { get; set; } // datetime
		[Column, NotNull] public string   code         { get; set; } // varchar(255)

		#region Associations

		/// <summary>
		/// fk_phone
		/// </summary>
		[Association(ThisKey="phone_number", OtherKey="phone_number", CanBeNull=false, KeyName="fk_phone", BackReferenceName="fkphones")]
		public person fkphone { get; set; }

		#endregion
	}

	// View
	[Table("user_summary")]
	public partial class user_summary
	{
	}

	// View
	[Table("user_summary_by_file_io")]
	public partial class user_summary_by_file_io
	{
	}

	// View
	[Table("user_summary_by_file_io_type")]
	public partial class user_summary_by_file_io_type
	{
	}

	// View
	[Table("user_summary_by_stages")]
	public partial class user_summary_by_stages
	{
	}

	// View
	[Table("user_summary_by_statement_latency")]
	public partial class user_summary_by_statement_latency
	{
	}

	// View
	[Table("user_summary_by_statement_type")]
	public partial class user_summary_by_statement_type
	{
	}

	// View
	[Table("version")]
	public partial class version
	{
	}

	// View
	[Table("wait_classes_global_by_avg_latency")]
	public partial class wait_classes_global_by_avg_latency
	{
	}

	// View
	[Table("wait_classes_global_by_latency")]
	public partial class wait_classes_global_by_latency
	{
	}

	// View
	[Table("waits_by_host_by_latency")]
	public partial class waits_by_host_by_latency
	{
	}

	// View
	[Table("waits_by_user_by_latency")]
	public partial class waits_by_user_by_latency
	{
	}

	// View
	[Table("waits_global_by_latency")]
	public partial class waits_global_by_latency
	{
	}

	// View
	[Table("x$host_summary")]
	public partial class x_host_summary
	{
	}

	// View
	[Table("x$host_summary_by_file_io")]
	public partial class x_host_summary_by_file_io
	{
	}

	// View
	[Table("x$host_summary_by_file_io_type")]
	public partial class x_host_summary_by_file_io_type
	{
	}

	// View
	[Table("x$host_summary_by_stages")]
	public partial class x_host_summary_by_stages
	{
	}

	// View
	[Table("x$host_summary_by_statement_latency")]
	public partial class x_host_summary_by_statement_latency
	{
	}

	// View
	[Table("x$host_summary_by_statement_type")]
	public partial class x_host_summary_by_statement_type
	{
	}

	// View
	[Table("x$innodb_buffer_stats_by_schema")]
	public partial class x_innodb_buffer_stats_by_schema
	{
	}

	// View
	[Table("x$innodb_buffer_stats_by_table")]
	public partial class x_innodb_buffer_stats_by_table
	{
	}

	// View
	[Table("x$innodb_lock_waits")]
	public partial class x_innodb_lock_waits
	{
	}

	// View
	[Table("x$io_by_thread_by_latency")]
	public partial class x_io_by_thread_by_latency
	{
	}

	// View
	[Table("x$io_global_by_file_by_bytes")]
	public partial class x_io_global_by_file_by_bytes
	{
	}

	// View
	[Table("x$io_global_by_file_by_latency")]
	public partial class x_io_global_by_file_by_latency
	{
	}

	// View
	[Table("x$io_global_by_wait_by_bytes")]
	public partial class x_io_global_by_wait_by_bytes
	{
	}

	// View
	[Table("x$io_global_by_wait_by_latency")]
	public partial class x_io_global_by_wait_by_latency
	{
	}

	// View
	[Table("x$latest_file_io")]
	public partial class x_latest_file_io
	{
	}

	// View
	[Table("x$memory_by_host_by_current_bytes")]
	public partial class x_memory_by_host_by_current_bytes
	{
	}

	// View
	[Table("x$memory_by_thread_by_current_bytes")]
	public partial class x_memory_by_thread_by_current_bytes
	{
	}

	// View
	[Table("x$memory_by_user_by_current_bytes")]
	public partial class x_memory_by_user_by_current_bytes
	{
	}

	// View
	[Table("x$memory_global_by_current_bytes")]
	public partial class x_memory_global_by_current_bytes
	{
	}

	// View
	[Table("x$memory_global_total")]
	public partial class x_memory_global_total
	{
	}

	// View
	[Table("x$processlist")]
	public partial class x_processlist
	{
	}

	// View
	[Table("x$ps_digest_95th_percentile_by_avg_us")]
	public partial class x_ps_digest_95th_percentile_by_avg_us
	{
	}

	// View
	[Table("x$ps_digest_avg_latency_distribution")]
	public partial class x_ps_digest_avg_latency_distribution
	{
	}

	// View
	[Table("x$ps_schema_table_statistics_io")]
	public partial class x_ps_schema_table_statistics_io
	{
	}

	// View
	[Table("x$schema_flattened_keys")]
	public partial class x_schema_flattened_keys
	{
	}

	// View
	[Table("x$schema_index_statistics")]
	public partial class x_schema_index_statistics
	{
	}

	// View
	[Table("x$schema_table_lock_waits")]
	public partial class x_schema_table_lock_waits
	{
	}

	// View
	[Table("x$schema_table_statistics")]
	public partial class x_schema_table_statistics
	{
	}

	// View
	[Table("x$schema_table_statistics_with_buffer")]
	public partial class x_schema_table_statistics_with_buffer
	{
	}

	// View
	[Table("x$schema_tables_with_full_table_scans")]
	public partial class x_schema_tables_with_full_table_scans
	{
	}

	// View
	[Table("x$session")]
	public partial class x_session
	{
	}

	// View
	[Table("x$statement_analysis")]
	public partial class x_statement_analysis
	{
	}

	// View
	[Table("x$statements_with_errors_or_warnings")]
	public partial class x_statements_with_errors_or_warnings
	{
	}

	// View
	[Table("x$statements_with_full_table_scans")]
	public partial class x_statements_with_full_table_scans
	{
	}

	// View
	[Table("x$statements_with_runtimes_in_95th_percentile")]
	public partial class x_statements_with_runtimes_in_95th_percentile
	{
	}

	// View
	[Table("x$statements_with_sorting")]
	public partial class x_statements_with_sorting
	{
	}

	// View
	[Table("x$statements_with_temp_tables")]
	public partial class x_statements_with_temp_tables
	{
	}

	// View
	[Table("x$user_summary")]
	public partial class x_user_summary
	{
	}

	// View
	[Table("x$user_summary_by_file_io")]
	public partial class x_user_summary_by_file_io
	{
	}

	// View
	[Table("x$user_summary_by_file_io_type")]
	public partial class x_user_summary_by_file_io_type
	{
	}

	// View
	[Table("x$user_summary_by_stages")]
	public partial class x_user_summary_by_stages
	{
	}

	// View
	[Table("x$user_summary_by_statement_latency")]
	public partial class x_user_summary_by_statement_latency
	{
	}

	// View
	[Table("x$user_summary_by_statement_type")]
	public partial class x_user_summary_by_statement_type
	{
	}

	// View
	[Table("x$wait_classes_global_by_avg_latency")]
	public partial class x_wait_classes_global_by_avg_latency
	{
	}

	// View
	[Table("x$wait_classes_global_by_latency")]
	public partial class x_wait_classes_global_by_latency
	{
	}

	// View
	[Table("x$waits_by_host_by_latency")]
	public partial class x_waits_by_host_by_latency
	{
	}

	// View
	[Table("x$waits_by_user_by_latency")]
	public partial class x_waits_by_user_by_latency
	{
	}

	// View
	[Table("x$waits_global_by_latency")]
	public partial class x_waits_global_by_latency
	{
	}

	public static partial class TableExtensions
	{
		public static group Find(this ITable<group> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static person Find(this ITable<person> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static rsvp_status Find(this ITable<rsvp_status> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}
	}
}
